def build_help_text(html: bool = False) -> str:
    if html:
        return (
            "🤖 <b>LazyTube 摘要查詢機器人</b>\n\n"
            "<b>指令說明：</b> (問號?代表有預設值)\n"
            "📌 <code>/nlm &lt;url&gt; &lt;自訂Prompt?&gt;</code> (1-3分)\n"
            "  → 獲取來源的文字摘要\n\n"
            "📌 <code>/pic &lt;url&gt; &lt;自訂Prompt?&gt;</code> (3-5分)\n"
            "  → 生成 <b>Portrait/Detailed</b> 圖片總結 (PNG)\n\n"
            "📌 <code>/note &lt;url&gt; &lt;自訂Prompt?&gt;</code> (3-5分)\n"
            "  → 生成詳細的 <b>Markdown</b> 總結報告檔案\n\n"
            "📌 <code>/batch &lt;url1,url2,...&gt; &lt;整合Prompt?&gt;</code> (3-8分)\n"
            "  → 一次匯入最多 20 個網址並產出<b>整合摘要</b>\n\n"
            "📌 <code>/slide &lt;url&gt; &lt;自訂Prompt?&gt; &lt;語言?&gt; &lt;格式?&gt;</code> (5-10分)\n"
            "  → 產生 <b>繁體中文</b> PDF (預設) 或 PPTX 簡報\n\n"
            "📌 <b>群組頻道訂閱：</b> (定時自動發送新片摘要)\n"
            "  → <code>/sub &lt;頻道網址&gt; [Prompt?] [小時?]</code>\n"
            "  → <code>/list</code>：查看目前追蹤清單\n"
            "  → <code>/unsub &lt;序號&gt;</code>：取消訂閱並移除排程\n\n"
            "💡 <b>Prompt 關鍵字快取：</b>\n"
            "可在 [自訂Prompt] 位置輸入關鍵字：\n"
            "• <code>detail</code>：詳細內容分析\n"
            "• <code>step</code>：整理教學步驟\n"
            "• <code>qa</code>：常見問答整理\n"
            "• <code>short</code>：極簡精華摘要\n"
            "• <code>poe</code>：POE 流派與地圖策略\n"
            "• <code>finance</code>：資深財經分析師模式\n\n"
            "<b>範例：</b>\n"
            "<code>/batch https://youtu.be/A, https://youtu.be/B 整合比較</code>\n"
            "<code>/sub https://youtube.com/@老高 10</code> (每天 10:00 檢查)\n"
            "<code>/nlm https://youtu.be/xxxxx</code>"
        )

    return (
        "🤖 LazyTube 摘要查詢機器人\n\n"
        "指令說明： (問號?代表有預設值)\n"
        "📌 /nlm <url> <自訂Prompt?> (1-3分)\n"
        "  → 獲取來源的文字摘要\n\n"
        "📌 /pic <url> <自訂Prompt?> (3-5分)\n"
        "  → 生成 Portrait/Detailed 圖片總結 (PNG)\n\n"
        "📌 /note <url> <自訂Prompt?> (3-5分)\n"
        "  → 生成詳細的 Markdown 總結報告檔案\n\n"
        "📌 /batch <url1,url2,...> <整合Prompt?> (3-8分)\n"
        "  → 一次匯入最多 20 個網址並產出整合摘要\n\n"
        "📌 /slide <url> <自訂Prompt?> <語言?> <格式?> (5-10分)\n"
        "  → 產生繁體中文 PDF (預設) 或 PPTX 簡報\n\n"
        "📌 群組頻道訂閱： (定時自動發送新片摘要)\n"
        "  → /sub <頻道網址> [Prompt?] [小時?]\n"
        "  → /list：查看目前追蹤清單\n"
        "  → /unsub <序號>：取消訂閱並移除排程\n\n"
        "💡 Prompt 關鍵字快取：\n"
        "可在 [自訂Prompt] 位置輸入關鍵字：\n"
        "• detail：詳細內容分析\n"
        "• step：整理教學步驟\n"
        "• qa：常見問答整理\n"
        "• short：極簡精華摘要\n"
        "• poe：POE 流派與地圖策略\n"
        "• finance：資深財經分析師模式\n\n"
        "範例：\n"
        "/batch https://youtu.be/A, https://youtu.be/B 整合比較\n"
        "/sub https://youtube.com/@老高 10\n"
        "/nlm https://youtu.be/xxxxx"
    )
